export type McpLibraryCategoryKey =
  | 'search'
  | 'research'
  | 'biomed'
  | 'ai'
  | 'hard-tech'
  | 'company'
  | 'market';

export type McpLibraryItem = {
  id: string;
  name: string;
  kind: 'MCP' | 'API' | 'MCP / API';
  category: McpLibraryCategoryKey;
  status: '推荐试用' | '适合自建' | '需订阅验证' | '观察';
  maturity: '官方' | '开源社区' | '社区实现' | '商业服务' | 'API 原生';
  pricing: '免费' | '免费层 + 付费' | '需订阅' | '按量计费' | '待确认';
  auth: '无需密钥' | 'API Key' | 'OAuth' | '平台账号' | '订阅账号' | '待确认';
  highlight: string;
  coverage: string;
  bestFor: string[];
  pevcUseCases: string[];
  safetyNote: string;
  url?: string;
  sourcePostId?: number;
  featured?: boolean;
};

export const mcpLibraryCategories: Array<{
  key: McpLibraryCategoryKey;
  label: string;
  short: string;
  description: string;
  tone: string;
}> = [
  {
    key: 'search',
    label: '搜索 / 抓取',
    short: 'Search',
    description: '把外部网页、新闻、PDF 和网页结构化内容接进 Agent。',
    tone: 'border-sky-300/35 bg-sky-300/10 text-sky-100',
  },
  {
    key: 'research',
    label: '论文 / 学术',
    short: 'Papers',
    description: '面向论文检索、引用链、主题监控和前沿技术跟踪。',
    tone: 'border-violet-300/35 bg-violet-300/10 text-violet-100',
  },
  {
    key: 'biomed',
    label: '生物医药',
    short: 'BioMed',
    description: '覆盖文献、临床试验、基因变异、药品安全等生命科学数据。',
    tone: 'border-emerald-300/35 bg-emerald-300/10 text-emerald-100',
  },
  {
    key: 'ai',
    label: 'AI / 开源生态',
    short: 'AI',
    description: '评估模型、数据集、开源项目活跃度和开发者生态。',
    tone: 'border-fuchsia-300/35 bg-fuchsia-300/10 text-fuchsia-100',
  },
  {
    key: 'hard-tech',
    label: '硬科技 / 工程',
    short: 'HardTech',
    description: '半导体、能源、标准、工程计算和技术可行性验算。',
    tone: 'border-amber-300/40 bg-amber-300/10 text-amber-100',
  },
  {
    key: 'company',
    label: '公司 / 尽调',
    short: 'Company',
    description: '工商、公告、融资、SEC 文件和公司事实核验。',
    tone: 'border-stone-200/35 bg-stone-200/10 text-stone-100',
  },
  {
    key: 'market',
    label: '市场 / 金融',
    short: 'Market',
    description: '价格、成交、宏观、行业指标和二级市场辅助数据。',
    tone: 'border-lime-300/35 bg-lime-300/10 text-lime-100',
  },
];

export const mcpLibraryItems: McpLibraryItem[] = [
  {
    id: 'biomcp',
    name: 'BioMCP',
    kind: 'MCP',
    category: 'biomed',
    status: '推荐试用',
    maturity: '开源社区',
    pricing: '免费',
    auth: '无需密钥',
    highlight: '生物医药投研最值得先试的 MCP。',
    coverage: 'PubMed、ClinicalTrials.gov、Europe PMC、ClinVar、OpenFDA 等公开生命科学数据源。',
    bestFor: ['创新药', 'IVD', '基因检测', '临床阶段判断'],
    pevcUseCases: ['梳理靶点与适应症文献', '查询临床试验进展', '核对药物安全与监管公开信息'],
    safetyNote: '适合查公开数据库；企业未公开管线、访谈纪要和患者数据不要直接输入。',
    url: 'https://github.com/genomoncology/biomcp',
    sourcePostId: 145,
    featured: true,
  },
  {
    id: 'arxiv-mcp',
    name: 'ArXiv MCP Server',
    kind: 'MCP',
    category: 'research',
    status: '推荐试用',
    maturity: '社区实现',
    pricing: '免费',
    auth: '无需密钥',
    highlight: '适合做前沿技术主题追踪。',
    coverage: 'arXiv 论文搜索、下载、摘要阅读、主题订阅与引用线索整理。',
    bestFor: ['AI', '机器人', '量子', '材料', '硬科技'],
    pevcUseCases: ['追踪赛道论文密度', '寻找核心研究团队', '形成技术路线时间线'],
    safetyNote: '论文结论需要二次核验，不要把模型摘要当成专家结论。',
    url: 'https://github.com/blazickjp/arxiv-mcp-server',
    sourcePostId: 145,
    featured: true,
  },
  {
    id: 'huggingface-mcp',
    name: 'Hugging Face MCP',
    kind: 'MCP',
    category: 'ai',
    status: '推荐试用',
    maturity: '官方',
    pricing: '免费层 + 付费',
    auth: '平台账号',
    highlight: 'AI/ML 投资看模型生态的高价值连接器。',
    coverage: '模型、数据集、Spaces、论文、下载量、社区讨论与文档。',
    bestFor: ['AI 应用', '基础模型', '开源生态', '数据集评估'],
    pevcUseCases: ['判断模型热度与活跃度', '核验 Demo 与 Space', '跟踪竞品模型路线'],
    safetyNote: '公开模型生态适合横向比较；不要上传客户私有数据集做测试。',
    url: 'https://huggingface.co/docs/hub/mcp-server',
    sourcePostId: 145,
    featured: true,
  },
  {
    id: 'github-mcp',
    name: 'GitHub MCP Server',
    kind: 'MCP',
    category: 'ai',
    status: '推荐试用',
    maturity: '官方',
    pricing: '免费层 + 付费',
    auth: 'OAuth',
    highlight: '开源项目活跃度和技术团队执行力的基础设施。',
    coverage: '代码搜索、Issue、PR、Release、贡献者、项目管理和仓库元数据。',
    bestFor: ['开源软件', 'Developer Tool', 'AI Infra', '安全工具'],
    pevcUseCases: ['检查项目活跃度', '识别真实贡献者', '分析 Issue 响应和版本节奏'],
    safetyNote: '授权范围要最小化；尽量只读公开仓库，谨慎连接私有代码库。',
    url: 'https://github.com/github/github-mcp-server',
    sourcePostId: 145,
    featured: true,
  },
  {
    id: 'wolfram-alpha',
    name: 'Wolfram Alpha MCP',
    kind: 'MCP / API',
    category: 'hard-tech',
    status: '推荐试用',
    maturity: '社区实现',
    pricing: '免费层 + 付费',
    auth: 'API Key',
    highlight: '硬科技投资里的“技术可行性验算器”。',
    coverage: '数学、物理、化学、工程计算、单位换算和公式推导。',
    bestFor: ['新能源', '核聚变', '量子计算', '新材料', '半导体'],
    pevcUseCases: ['验算 LCOE', '核对 Lawson 判据', '估算退相干时间与门操作时间', '验证材料性能上限'],
    safetyNote: '适合做 sanity check；关键投资判断仍需专家复核和原始模型验证。',
    url: 'https://products.wolframalpha.com/api',
    sourcePostId: 145,
    featured: true,
  },
  {
    id: 'microchip-mcp',
    name: 'Microchip MCP',
    kind: 'MCP',
    category: 'hard-tech',
    status: '观察',
    maturity: '社区实现',
    pricing: '待确认',
    auth: '待确认',
    highlight: '半导体产品、Datasheet 和参考设计检索入口。',
    coverage: 'Microchip 芯片产品、规格、Errata、参考设计和应用文档。',
    bestFor: ['半导体', 'IoT 硬件', '汽车电子', '工业控制'],
    pevcUseCases: ['核对芯片规格', '比较产品线覆盖', '辅助判断供应链替代方案'],
    safetyNote: '作为工程资料入口使用；关键 BOM、价格和交付周期仍要向供应链渠道核验。',
    sourcePostId: 145,
  },
  {
    id: 'ieee-2030-5',
    name: 'IEEE 2030.5 MCP',
    kind: 'MCP',
    category: 'hard-tech',
    status: '观察',
    maturity: '社区实现',
    pricing: '待确认',
    auth: '待确认',
    highlight: '智能能源通信标准的结构化导航。',
    coverage: 'IEEE 2030.5 智能能源协议对象、接口和 HATEOAS 导航。',
    bestFor: ['虚拟电厂', '储能', '智能电网', '充电桩'],
    pevcUseCases: ['理解能源通信协议', '核验产品是否接近标准接口', '辅助访谈技术团队'],
    safetyNote: '标准解释不能替代合规意见；商业项目仍需查看授权标准文本。',
    sourcePostId: 145,
  },
  {
    id: 'exa-mcp',
    name: 'Exa MCP',
    kind: 'MCP',
    category: 'search',
    status: '推荐试用',
    maturity: '商业服务',
    pricing: '免费层 + 付费',
    auth: 'API Key',
    highlight: '语义搜索和网页发现能力强，适合找“相似公司/相似论文/相似产品”。',
    coverage: '网页搜索、语义相似搜索、内容提取和研究型搜索。',
    bestFor: ['竞品发现', '主题研究', '海外信息检索'],
    pevcUseCases: ['找相似公司', '生成赛道公司长名单', '补充专家访谈前材料'],
    safetyNote: '联网搜索会访问外部服务，不要把保密项目名称和未公开材料整段发送。',
    url: 'https://github.com/exa-labs/exa-mcp-server',
    sourcePostId: 145,
  },
  {
    id: 'firecrawl-mcp',
    name: 'Firecrawl MCP',
    kind: 'MCP',
    category: 'search',
    status: '推荐试用',
    maturity: '商业服务',
    pricing: '免费层 + 付费',
    auth: 'API Key',
    highlight: '把网页转成 Agent 友好的 Markdown / 结构化内容。',
    coverage: '网页抓取、站点爬取、结构化抽取、Markdown 转换。',
    bestFor: ['官网分析', '竞品文档', '政策网页', '产品资料'],
    pevcUseCases: ['抽取公司官网信息', '整理竞品产品页', '批量阅读政策或招投标公告'],
    safetyNote: '注意目标网站条款和频率限制；不要抓取需要登录或无授权的数据。',
    url: 'https://github.com/mendableai/firecrawl-mcp-server',
    sourcePostId: 145,
  },
  {
    id: 'playwright-mcp',
    name: 'Playwright MCP',
    kind: 'MCP',
    category: 'search',
    status: '适合自建',
    maturity: '官方',
    pricing: '免费',
    auth: '无需密钥',
    highlight: '让 Agent 操作浏览器，适合做站点验收和交互式信息采集。',
    coverage: '浏览器打开、点击、表单、截图、页面结构读取和自动化测试。',
    bestFor: ['网站验收', '竞品体验', '投后运营检查'],
    pevcUseCases: ['检查被投公司官网流程', '批量截图竞品页面', '自动化上线前 smoke test'],
    safetyNote: '浏览器自动化权限很高；登录后台、支付、删除等操作要人工确认。',
    url: 'https://github.com/microsoft/playwright-mcp',
    sourcePostId: 145,
  },
  {
    id: 'semantic-scholar',
    name: 'Semantic Scholar API',
    kind: 'API',
    category: 'research',
    status: '适合自建',
    maturity: 'API 原生',
    pricing: '免费',
    auth: 'API Key',
    highlight: '论文引用、作者和影响力线索适合封装成内部 MCP。',
    coverage: '论文、作者、引用、参考文献、领域、摘要和开放元数据。',
    bestFor: ['学术影响力', '技术源头', '专家地图'],
    pevcUseCases: ['寻找核心 PI', '追踪引用网络', '判断论文是否进入产业化阶段'],
    safetyNote: '公开学术元数据适合初筛，专家判断仍需结合访谈和产业验证。',
    url: 'https://api.semanticscholar.org',
    sourcePostId: 145,
  },
  {
    id: 'openalex',
    name: 'OpenAlex API',
    kind: 'API',
    category: 'research',
    status: '适合自建',
    maturity: 'API 原生',
    pricing: '免费',
    auth: '无需密钥',
    highlight: '开放学术图谱，适合做机构、作者、论文和概念网络。',
    coverage: 'Works、Authors、Institutions、Sources、Concepts、Funders 等开放元数据。',
    bestFor: ['高校成果转化', '研究机构分析', '专家网络'],
    pevcUseCases: ['看机构研究方向', '找同领域作者群', '判断论文主题迁移趋势'],
    safetyNote: '元数据覆盖和归并存在误差，正式报告要引用原始来源。',
    url: 'https://docs.openalex.org',
    sourcePostId: 145,
  },
  {
    id: 'sec-edgar',
    name: 'SEC EDGAR / EdgarTools',
    kind: 'API',
    category: 'company',
    status: '适合自建',
    maturity: 'API 原生',
    pricing: '免费',
    auth: '无需密钥',
    highlight: '海外上市公司公告和财务披露的基础数据源。',
    coverage: '10-K、10-Q、S-1、8-K、公司事实、财务报表和披露文本。',
    bestFor: ['海外上市公司', '可比公司', '退出路径', '财务披露'],
    pevcUseCases: ['找可比公司风险披露', '拆 S-1 商业模式', '做退出案例和财务指标对照'],
    safetyNote: '公告数据适合引用，但自动抽取的表格和指标要人工复核。',
    url: 'https://www.sec.gov/edgar/sec-api-documentation',
    sourcePostId: 145,
  },
  {
    id: 'brave-search',
    name: 'Brave Search MCP',
    kind: 'MCP',
    category: 'search',
    status: '推荐试用',
    maturity: '官方',
    pricing: '免费层 + 付费',
    auth: 'API Key',
    highlight: '通用网页搜索入口，适合作为 Agent 的基础外部信息源。',
    coverage: '网页、新闻、图片、视频等搜索结果和摘要信息。',
    bestFor: ['通用调研', '新闻监控', '公开信息补全'],
    pevcUseCases: ['补充公司公开动态', '搜索政策新闻', '查找第三方报道'],
    safetyNote: '搜索结果不等于事实；需要交叉验证来源质量和发布时间。',
    url: 'https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search',
    sourcePostId: 145,
  },
  {
    id: 'financial-datasets',
    name: 'Financial Datasets MCP',
    kind: 'MCP',
    category: 'market',
    status: '观察',
    maturity: '商业服务',
    pricing: '免费层 + 付费',
    auth: 'API Key',
    highlight: '把金融市场数据接给 Agent，用于二级指标和可比公司辅助分析。',
    coverage: '股票价格、财务指标、新闻、公司信息和部分市场数据。',
    bestFor: ['可比公司', '二级市场验证', '行业景气度'],
    pevcUseCases: ['跟踪可比公司估值', '观察产业链上市公司信号', '辅助退出路径判断'],
    safetyNote: '金融数据源需要核对授权和延迟；不要作为投资建议自动输出。',
    url: 'https://github.com/financial-datasets/mcp-server',
    sourcePostId: 145,
  },
];

export function getMcpLibraryItemsByCategory(category: McpLibraryCategoryKey) {
  return mcpLibraryItems.filter((item) => item.category === category);
}

export function getMcpLibraryCategory(category: McpLibraryCategoryKey) {
  return mcpLibraryCategories.find((item) => item.key === category);
}
